// <auto-generated />
using System;
using MSHCAccesData;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MS.HC.AccesData.Migrations
{
    [DbContext(typeof(HCTemplateContext))]
    [Migration("20200521214957_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HCTemplateDomain.Entities.HistoriasClinicas", b =>
                {
                    b.Property<Guid>("HistoriaClinicaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DetalleDeConsulta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("MedicoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PacienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TurnoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("HistoriaClinicaId");

                    b.ToTable("HistoriasClinicas");
                });
#pragma warning restore 612, 618
        }
    }
}
